name: RiddleBot
version: '${project.version}'
main: me.awie1000.riddlebot.RiddleBot
api-version: 1.20
commands:
  hunt:
    description: "Participate in Scavenger Hunts"
    usage: "/hunt [submit/list]"
  hunt-admin:
    description: "Create/Run Scavenger Hunts"
    usage: "/hunt-admin [start/stop/generate]"
    permission: riddlebot.commands.huntadmin
